CREATE DATABASE myutils CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE myutils;
CREATE TABLE todo (id INT NOT NULL AUTO_INCREMENT, task VARCHAR(255) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB;
CREATE TABLE done (id INT NOT NULL AUTO_INCREMENT, task VARCHAR(255) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB;